exclude = [
  '^https://github\.com/llvm/llvm-project/releases/download/llvmorg-',  # LLVM download urls assembled from this
  "^https://github.com/danmar/cppcheck/archive/refs/tags/"  # Cppcheck download urls assembled from this
]
